apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::427860451640:role/eksctl-simple-jwt-api-nere-nodegr-NodeInstanceRole-1A267PYYM7EN4
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2023-04-03T18:34:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1734"
  uid: 66cc313c-809d-4401-a7ce-982f95690f8e
